///This program is intended to show the unrecoverable error.
fn main() {
    let count: vec<i32> = vec![1,2,3];
    print!("element of a vector is {}:",count[3]);
}
